version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=azerty
      - POSTGRES_DB=database
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:azerty@172.19.0.2:5432/database
      - PORT=4000
      - JWT_SECRET=7f!jf7O$$Mjz4fWr%43c9IcRqfMQcL!TKPE!Lfwe
      - SERVER_URL=https://bookly.ovh
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=azerty 
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "4000:4000"
networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
