services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/letsencrypt:/etc/letsencrypt:ro
       - uploads_data:/usr/share/nginx/uploads
    networks:
      - internal
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=azerty
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - uploads_data:/app/uploads

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=azerty
      - POSTGRES_DB=database
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: