version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=azerty 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "4000:4000"
networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
