version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:azerty@postgres:5432/database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=database
      - DB_USER=postgres
      - DB_PASSWORD=azerty
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "4000:4000"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=azerty
      - POSTGRES_DB=database
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
