FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json tsconfig.json prisma ./

RUN npm install

RUN npx prisma generate

COPY ./src ./src

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/index.js"]
